#controller_joint_names: ['', 'backleft', 'frontleft', 'frontright', 'backright', ]

# The joint state controller handles publishing transforms for any moving joints

rover_nav:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Velocity Controllers -----------------------------------------
  backleft_controller:
    type: effort_controllers/JointVelocityController
    joint: backleft
    pid: {p: 100.0, i: 10.0, d: 0.01}

  backright_controller:
    type: effort_controllers/JointVelocityController
    joint: backright
    pid: {p: 100.0, i: 10.0, d: 0.01}

  frontleft_controller:
    type: effort_controllers/JointVelocityController
    joint: frontleft
    pid: {p: 100.0, i: 10.0, d: 0.01}

  frontright_controller:
    type: effort_controllers/JointVelocityController
    joint: frontright
    pid: {p: 100.0, i: 10.0, d: 0.01}

