# footprint: [[-0.50165, -0.384175], [-0.50165, 0.384175], [0.50165, 0.384175], [0.50165, -0.384175]]
footprint: [[-0.49, -0.44], [-0.49, 0.44], [0.49, 0.44], [0.49, -0.44]]



robot_base_frame: robot_footprint
update_frequency: 3.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.08

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser  #, laser2
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true, obstacle_range: 5.5}
    #laser2: {}
inflation_global:
    inflation_radius: 0.5
    # inflation_radius: 0.65
inflation_local:
    inflation_radius: 0.1







