scaled_pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - scorbot_joint_1
    - scorbot_joint_2
    - scorbot_joint_3
    - scorbot_joint_4
    - scorbot_joint_5
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.5
    scorbot_joint_1: {trajectory: 0.1, goal: 0.1}
    scorbot_joint_2: {trajectory: 0.1, goal: 0.1}
    # scorbot_joint_3: {trajectory: 0.1, goal: 0.1}
    # scorbot_joint_4: {trajectory: 0.1, goal: 0.1}
    # scorbot_joint_5: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
